config/routes.rb
Rails.application.routes.draw do

  resources 'users',only:[:show], :path => "my-profile"
  resources 'projects', only:[:index,:new,:create,:show,:edit,:destroy,:update ], :path => "dashboard"
  resources :housings 
  scope 'admin', module: 'admin', as: 'admin' do
    resource 'pannel'
  end

  resources :projects do 
  resources :housings 
  end 

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  root to: "statics#home"

  scope controller: :statics do
    get :contact
    post :create
  
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :housings
  validates :title, presence: true
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_user_project, only: [:show]
    
  def index
    @projects = Project.where(user_id: current_user.id) 
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    @project_title = @project.title 
    @project_localization = @project.localization 
    @project_comment = @project.comment
    @project_id = @project.user_id.to_i
    @housings = Housing.where(project_id: params[:id]) 
  end

  def create
    @project = Project.create(
    title: params[:project][:title],
    comment: params[:project][:comment],
    localization: params[:project][:localization],
    user_id: current_user.id
    )
    flash[:notice] = "Création de projet réussi 👌"
    redirect_to projects_path
  end

  def destroy 
    @project = Project.find(params[:id])
    @project_housings = Housing.where(project_id: @project.id)
    @project_housings.each do |project|
      project.destroy
    end
    @project.destroy
    flash[:notice] = "Suppression de projet réussi !"
    redirect_to projects_path
  end 

  def edit
    @project = Project.find(params[:id])
  end
    
  def update
    @project = Project.find(params[:id])
    project_params = params.require(:project).permit(:title, :localization, :comment)
    @project.update(project_params)
    flash[:notice] = "Édition du projet réussi 👌"
    redirect_to project_path
  end 

  private

  def set_user_project
    @project_user = Project.find(params[:id].to_i).user_id

    if current_user.present? == false
      redirect_to root_path
    elsif @project_user.to_i == current_user.id
    else
      redirect_to projects_path
    end
  end
        
end

app/helpers/projects_helper.rb
module ProjectsHelper
def nil? 
    housing.offer_profitability == nil 
end

end

app/views/projects/edit.html.erb
<section>
  <div class="py-15 d-flex flex-column container level-3 min-vh-100">
    <div class="row align-items-center justify-content-center my-auto">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <div class=" card-shadow">
          <div class="card-header bg-white pb-0">
            <%= link_to project_path(@project), class:'w-100 d-flex justify-content-start' do %>
              <i class="fas fa-arrow-left m-1">
              </i>  Retour
            <%end%>
            <h4 class="fw-light mb-5">Editer un <span class="fw-bold mb-5">projet </span></h4>
            <div class="card-body">
              <%=form_for @project do |f| %>
                <div class="form-group ">
                  <label>Titre du projet :</label><br />
                  <%= f.text_field :title, class: "form-control"%>
                </div>
                <div class="form-group mt-3">
                  <label>Lieu :</label>
                  <%= f.text_field :localization, class: "form-control" %>
                </div>
                <div class="form-group mt-3">
                  <label>Note :</label>
                  <%= f.text_field :comment, class: "form-control" %>
                </div>
                <div class="form-group mt-5 d-grid mb-2ns">
                  <button class="btn btn-lg btn-primary" type='submit'>Modifier le projet</button>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/index.html.erb
<div class="main-div card-shadow">
<div class="pt-5 px-0">
    <div class="container" style="margin: 30px;">
      <div class="row justify-content-between align-items-center gutter-3 gutter-lg-5">
        <div class="col-lg-14">
            <%= link_to root_path, class:'w-100 d-flex justify-content-start text-white' do %>
              <i class="fas fa-arrow-left m-1">
              </i>  Accueil
            <%end%>
          <h2 class="fw-light mb-4">Bienvenue sur <span class="fw-bold mb-4">vos projets</span></h2>
          <p>Ici, vous pouvez retrouver tous vos projets locatifs en cours, en créer de nouveaux et accéder au comparateur de logements. </p>
          <div class="warning-area"><p><span style="font-size:2rem; font-weight: 600;">&#9888;</span> Attention : notre outil permet de conseiller nos utilisateurs en facilitant la comparaison de biens immobiliers selon certains critères déterminés par les utilisateurs eux-mêmes. <br />
          Nous ne pourrons donc être tenus pour responsables des conséquences des achats effectués. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-0 py-xl-5 bg-white">
    <div class="container">
      <div class="row g-3 g-xl-5">
        <%@projects.each do |project|%>
          <div class="col-md-6 col-lg-4 aos-init aos-animate" data-aos="fade-up">           
            <%= link_to project_path(project.id), class:"card border card-arrow" do %>
              <div class="card-header">
                <h3 class="card-title"><%=project.title%></h3>
              </div>
              <div class="card-footer">
                <div class="d-flex align-items-center">
                  <div class="ms-2">
                    <p class="mb-0 lh-1"><%=project.localization %></p>
                    <p class="mb-0 lh-1"><%= truncate(project.comment, length:30 )%></p>
                  </div>
                </div>           
              </div>
            <%end%>
          </div>
        <%end%>        
          <div class="pt-3 px-5">
            <div class="container">
              <div class="row justify-content-end align-items-center gutter-3 gutter-lg-5 ">
                <div class="col-lg-3 ">
                  <%=link_to 'Créer un nouveau projet', new_project_path , class: 'btn btn-primary rounded'%>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<section>
  <div class="py-15 d-flex flex-column container level-3 min-vh-100">
    <div class="row align-items-center justify-content-center my-auto">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <div  class=" card-shadow">
          <div class="card-header bg-white pb-0">
            <%= link_to projects_path, class:'w-100 d-flex justify-content-start' do %>
              <i class="fas fa-arrow-left m-1">
              </i>  Retour
            <%end%>
            <h4 class="fw-light mb-5 text-center">Créer un nouveau  <span class="fw-bold mb-5">projet </span></h4>
            <div class="card-body">
              <%= form_with(model: @project, url: projects_path, method: "post", local: true) do |f| %>
                <%= label_tag :title, "Titre du projet *:", class:"form-label" %>
                <%= f.text_field :title, class: 'form-control', value: @project.title%> 
                <br />
                <%= label_tag :localization, "Localisation du bien :", class:"form-label" %>
                <%= f.text_field :localization, class: 'form-control', value: @project.localization %> 
                <br />
                <%= label_tag :comment, "Vos notes :", class:"form-label" %>
                <%= f.text_area :comment, class: 'form-control', value: @project.comment %>
                <br />
                <div class='col text-lg-end' style="margin-top: 15px;">
                  <%= f.submit "Créer", class:'btn btn-primary rounded' %>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<div class="main-div card-shadow">
  <div class="pt-5 px-0">
    <div class="container">
      <div class="row justify-content-between align-items-center gutter-3 gutter-lg-5">
        <div class="col-lg-14">
            <%= link_to projects_path, class:'w-100 d-flex justify-content-start text-white' do %>
              <i class="fas fa-arrow-left m-1">
              </i>  Retour
            <%end%>
          <h2 class="fw-light mb-4">Mon <span class="fw-bold mb-5">Projet: </span> <%=@project.title%></h2>
          <p>Ici, vous avez accès aux logements que vous avez ajouté à votre projet, vous pouvez les modifier, <br /> remplir le formulaire de rentabilité et supprimer un logement.</p>
          <br />
          <p><span style="font-weight:700">Localisation:</span> <%=@project.localization%></p>    
          <p><span style="font-weight:700">Mes remarques:</span> <%=@project_comment%></p>   
          <div class="warning-area"><p class="small"><span style="font-size: 2rem; margin-right: 10px"> &#9432;</span>Notre outil présente les biens en fonction de leur rentabilité nette : il s'agit d'une unité permettant de mesurer les potentiels gains d'un bien immobilier et de les comparer à d'autres biens en fonction de vos réponses à notre formulaire . Ainsi, plus la rentabilité d'un bien est élevée, plus les bénéfices peuvent être importants. <br />
            Veillez donc à saisir des information réalistes. Nous estimons qu'un bien est intéressant à partir de 4% de rentabilité. <br /><br />
            <span style=" font-size: 1rem; margin-right: 10px">&#9888;</span>La rentabilité nette ne prend pas en compte votre fiscalité, qui dépend de vos informations personnelles. N'hésitez pas à vous renseigner pour bénéficier des meilleurs avantages. </p>
          </div>      
        </div>
        <div class='col-sm text-lg-end'>
        <%= link_to edit_project_path, class:"btn btn-light m-1 rounded" do %>Editer votre projet<i class="fas fa-pencil-alt  ms-1"></i> <%end%>
        <%=link_to project_path, {class:'btn btn-light m-1 rounded',  'data-confirm' => 'Etes-vous sûrs', 'data-method' => 'DELETE'} do %>
        Supprimer votre projet <i class="fas fa-times fa-lg ms-1"></i> 
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="py-0 py-xl-5 bg-white">
    <div class="container">
      <div class="col pt-5 mt-5">
        <ul class="list-unstyled">
          <%@housings.each do |housing|%>
            <li>
              <div id="<%=housing.id%>">
                <%= link_to project_housing_path(housing.project_id, housing.id), class:"card bg-white card-hover-border", style:'color: rgb(173 81 81 / 98%)' do %>
                  <div class="card-body  py-2">
                    <div class=" d-flex flex-lg-column">
                      <div class="d-flex-lg-column ">
                        <div class='d-flex justify-content-between'>
                          <div class='order-1'>
                            <p class="fs-lg fw-light mb-0"><%= housing.property_category%>  <i class="fas fa-circle" style="font-size: 0.3rem"></i>   <%=housing.ad_price%>€  <i class="fas fa-circle" style="font-size: 0.3rem"></i>  <%=  truncate(housing.localization, length:10 )%>  </p>
                            <ul class="list-inline list-inline-separated text-muted">
                              <li class="list-inline-item"><%= housing.comment %></li>
                            </ul>
                          </div>
                          <div class='order-2 text-center p-0 '>
                            <% if housing.offer_profitability.nil? %>
                            <%else%>
                              <% if housing.offer_profitability >= 0 %>
                                <p class='pt-2'>Rentabilité estimée : <span style=' color: green'> <%=housing.offer_profitability.round(2)%> % </span></p>
                              <% else %>
                                <p class='pt-2'>Rentabilité estimée : <span style=' color: red'> <%=housing.offer_profitability.round(2)%> % </span></p>
                              <%end%>
                            <%end%>
                          </div>
                          <div class=" order-3 text-md-end p-0">
                            <div class="col d-flex">
                              <%= button_to  edit_project_housing_path(housing.project_id, housing.id), method: :get, class:' btn btn-outline-primary rounded ' do%>
                                <i class="fas fa-pencil-alt fa-lg   ms-1"></i>
                              <%end%>

                             <%= button_to  housing_path(housing.id), method: :delete, class:'btn btn-primary  rounded ms-2', remote: true do %><i class="fas fa-times ms-1"></i> 

                             <%end%>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <%end%>
              </div>
            </li>
          <%end%>      
        </ul>
      </div>
      <div class='col d-flex justify-content-end bg-white'>
        <%=link_to new_project_housing_path(@project), class: 'btn btn-primary rounded m-5' do %> <i class="fas fa-plus"></i>  Ajouter un logement <%end%>
      </div>
    </div>      
  </div>
</div>