config/routes.rb
Rails.application.routes.draw do

  resources 'users',only:[:show], :path => "my-profile"
  resources 'projects', only:[:index,:new,:create,:show,:edit,:destroy,:update ], :path => "dashboard"
  resources :housings 
  scope 'admin', module: 'admin', as: 'admin' do
    resource 'pannel'
  end

  resources :projects do 
  resources :housings 
  end 

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  root to: "statics#home"

  scope controller: :statics do
    get :contact
    post :create
  
  end
end

app/models/housing.rb
class Housing < ApplicationRecord
  belongs_to :project
  has_one :user, through: :project

  validates :ad_price, presence: true
  validates :property_category, presence: true
  validates :localization, presence: true
end

app/controllers/housings_controller.rb
class HousingsController < ApplicationController

  def index
  end

  def destroy   
    @housing = Housing.find(params[:id])

    @project_user = Project.find(Housing.find(params[:id]).project_id.to_i).user_id

    if current_user.present? == false
      redirect_to root_path
    elsif @project_user.to_i == current_user.id
      @project = Project.find(@housing.project_id)
      @housing.destroy
  
      flash[:notice] = "Suppression de logement réussie !"  
    else
      redirect_to projects_path
    end


  end

  def new
    @project_user = Project.find(params[:project_id].to_i).user_id

    if current_user.present? == false
      redirect_to root_path
    elsif @project_user.to_i == current_user.id
      @project= Project.find(params[:project_id])
      @housing = Housing.new 
    else
      redirect_to projects_path
    end
  end

  def edit
    @housing = Housing.find(params[:id])

    @project_user = Project.find(@housing.project_id.to_i).user_id
    
    if current_user.present? == false
      redirect_to root_path
    elsif @project_user.to_i == current_user.id
    else
      redirect_to projects_path
    end
  end

  def show
    @housing = Housing.find(params[:id])

    @project_user = Project.find(@housing.project_id.to_i).user_id

    if current_user.present? == false
      redirect_to root_path
    elsif @project_user.to_i == current_user.id
      @housing_title =@housing.property_category
      @housing_price = @housing.offer_price
      @housing_localization = @housing.localization
      @housing_profitability = @housing.offer_profitability
    else
      redirect_to projects_path
    end


  end

  def create
    @housing = Housing.create(
      ad_price: (params[:housing][:ad_price]).to_i,
      property_category: (params[:housing][:property_category]).to_s,
      localization: (params[:housing][:localization]).to_s,
      area: 0,
      offer_price:  (params[:housing][:ad_price]).to_i,
      repairs_price: 0,
      annual_rent: 0,
      notary_fees: ((params[:housing][:ad_price]).to_i * 0.08).to_i,
      agency_fees:  ((params[:housing][:ad_price]).to_i * 0.08).to_i,
      pno_insurance: 0,
      property_tax: 0,
      rental_management: 0,
      rental_unpayment_insurance: 0,
      building_co_tax: 0,
      maintenance_percentage: 2,
      rental_vacancy: 6,
      project_id: params[:project_id]
    )
    
    flash[:notice] = "Création de logement réussie 👌"
    redirect_to project_path(@housing.project_id)
  end

  def update
    @housing = Housing.find(params[:id])  
        
    def calculate_profitability(price)
      housing = Housing.find(params[:id])

      if(housing.pno_insurance == true)
        pno = 0.03
      else
        pno = 0
      end

      if(housing.rental_management == true)
        management = 0.07
      else
        management = 0
      end

      if(housing.rental_unpayment_insurance == true)
        unpayment = 0.04
      else
        unpayment = 0
      end

      if(housing.new_property == true)
        notary_fees = housing.offer_price*0.03
      end

      fees = housing.property_tax + (price * (housing.maintenance_percentage/100)) + housing.building_co_tax + (housing.annual_rent * management) + (housing.annual_rent * pno) + (housing.annual_rent * unpayment)
      profitability = (housing.annual_rent*(1-(housing.rental_vacancy/100)) - fees) * 100 / (price  + housing.repairs_price + housing.notary_fees + housing.agency_fees)
    end
    
    @housing.update(           
      ad_price: params[:housing][:ad_price],
      property_category: params[:housing][:property_category],
      localization: params[:housing][:localization],
      comment: params[:housing][:comment],
      area: params[:housing][:area],
      ad_url: params[:housing][:ad_url],
      offer_price:  params[:housing][:offer_price],
      repairs_price: params[:housing][:repairs_price],
      annual_rent: params[:housing][:annual_rent],
      notary_fees: params[:housing][:notary_fees],
      agency_fees: params[:housing][:agency_fees],
      pno_insurance: params[:housing][:pno_insurance],
      property_tax: params[:housing][:property_tax],
      rental_management: params[:housing][:rental_management],
      rental_unpayment_insurance: params[:housing][:rental_unpayment_insurance],
      building_co_tax: params[:housing][:building_co_tax],
      maintenance_percentage: params[:housing][:maintenance_percentage],
      rental_vacancy: params[:housing][:rental_vacancy],
      new_property: params[:housing][:new_property]
    )

    

    @housing.update(
      ad_profitability: calculate_profitability(Housing.find(params[:id]).ad_price),
      offer_profitability: calculate_profitability(Housing.find(params[:id]).offer_price)
    )
        
    if 
      flash[:notice] = "Édition du logement réussi 👌"
      redirect_to project_housing_path
    elsif 
      flash[:alert] = "Erreur lors de l'édition du logement"
    end
  end

  private


end

app/helpers/housings_helper.rb
module HousingsHelper
end

app/views/housings/destroy.js.erb
document.getElementById('<%= @housing.id %>').remove();

app/views/housings/edit.html.erb
<div class="form-body">
  <%= form_with(model: @housing, url: project_housing_path, method: "put", local: true, class:'form-wrapper card-shadow') do |f| %>
    <div class="form-title">    
  <%= link_to project_housing_path(@housing.project_id, @housing.id), class:'w-100 d-flex justify-content-start' do %>
    <i class="fas fa-arrow-left m-1">
    </i>  Retour
  <%end%>
      <h4>Formulaire</h4>
      <div class="stepper">
        <div class="step">
          <div class="step-label">
            Annonce
          </div>
          <div class="step-bullet">
            1
          </div>
        </div>
        <div class="step">
          <div class="step-label">
            Logement
          </div>
          <div class="step-bullet">
            2
          </div>
        </div>
        <div class="step">
          <div class="step-label">
            Charges
          </div>
          <div class="step-bullet">
            3
          </div>
        </div>
        <div class="step">
          <div class="step-label">
            Invest
          </div>
        <div class="step-bullet">
          4
        </div>
        </div>
        <div class="step">
          <div class="step-label">
            Offre
          </div>
          <div class="step-bullet">
            5
          </div>
        </div>
      </div>
    </div>

    <div class="form-content">
      <div class="slide active">
        <h6>Références de l'annonce :</h6>

        <div class="my-input">      
          <%= label_tag(:ad_url, "Lien vers l'annonce :") %>
          <%= f.url_field :ad_url, class: 'form-control', value: @housing.ad_url %>
        </div>
        
        <div class="my-input">          
          <%= label_tag(:ad_price, "Prix de l'annonce (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field  :ad_price, class: 'form-control', value: @housing.ad_price, min:"0", required: true %> 
        </div>

        <div class="my-input">
          <%= label_tag(:property_category, "Type de bien :")  %>
          <br />
          <%= f.select :property_category, ['Studio', 'T1', 'T1bis', 'T2', 'T2bis', 'T3', 'T4', 'T5', 'T6', 'Immeuble', 'Autre' ], class: 'form-control', value: @housing.property_category %> 
        </div>
        
        <div class="my-input">
          <%= label_tag(:localization, "Localisation du bien :") %>
          <%= f.text_field :localization, class: 'form-control', value: @housing.localization, required: true  %> 

          <div class="warning-area">
              <p><span style="font-size:1.2rem">&#9432;</span> Nous vous conseillons de vérifier sur plusieurs annonces le prix des biens similaires afin de voir s'il n'y a pas d'incohérence avec le prix annoncé. <br /> N'hésitez pas à questionner le propriétaire ou l'agence lors de la visite. </p>
          </div>
        </div>
      </div>

      <div class="slide">
        <h6>Caractéristiques du bien :</h6>

        <div class="my-input">
          <%= label_tag(:area, "Surface habitable (en m²) :")%>  <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :area, class: 'form-control', value: @housing.area, min:"0", required: true  %>
        </div>

        <div class="warning-area">
          <p><span style="font-size:1.2rem">&#9432;</span> Nous vous conseillons de vérifier le prix au mètre carré pour la localisation du bien. </p>
        </div>

        <div class="my-input">
          <%= label_tag(:repairs_price, "Prix des travaux (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :repairs_price, class: 'form-control', value: @housing.repairs_price, min:"0", required: true  %>
        </div>

        <div class="my-input">
          <div class="d-flex align-items-center">
          <%= f.check_box :new_property %>
          <%= label_tag(:new_property, "Neuf", class:"check-label") %>
          </div>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> Lors de la visite, il faut impérativement poser des questions sur l'état du bien et plus particulièrement trois éléments qui peuvent très rapidement faire grimper le coût des travaux à prévoir:</p>
            <ul> 
            <li>la toiture (environ 250€/m² de toit), </li>
            <li>la façade (environ 30€/m² de mur), </li>
            <li>la chaudière (à condensation gaz : entre 3000 - 6000 €, classique: entre 500 - 2500€). </li>
            </ul>
          </div>          
        </div>
      </div>

      <div class="slide">
        <h6>Charges :</h6>
              
        <div class="my-input">
          <%= label_tag(:building_co_tax, "Charges de copropriété (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :building_co_tax, class: 'form-control', value: @housing.building_co_tax, min:"0", required: true  %>
        </div>

        <div class="my-input">
          <%= label_tag(:property_tax, "Taxe foncière (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :property_tax, class: 'form-control', value: @housing.property_tax, min:"0", required: true  %>
        </div>

        <div class="my-input">
          <div class="d-flex align-items-center">
            <%= f.check_box :pno_insurance %>
            <%= label_tag(:pno_insurance, "Assurance PNO ", class:"check-label") %>
          </div>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> L'assurance Propriétaire Non Occupant garantit au propriétaire bailleur une couverture équivalente à la multirisque habitation. <br />
            Elle correspond généralement à environ 7% du loyer. </p>
          </div>       
        </div>

        <div class="my-input">
          <div class="d-flex align-items-center">
            <%= f.check_box :rental_unpayment_insurance %>
            <%= label_tag(:rental_unpayment_insurance, "Assurance pour loyers impayés", class:"check-label") %>
          </div>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> L'assurance pour loyers impayés garantit le versement du loyer au propriétaire en cas de défault de paiement par le locataire. <br />
            Elle correspond généralement à environ 7% du loyer. </p>
          </div>       
        </div>         
      </div>

      <div class="slide">
        <h6>Investissement :</h6>

        <div class="my-input">
          <%= label_tag(:annual_rent, "Loyer annuel complet (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :annual_rent, class: 'form-control', value: @housing.annual_rent, min:"0", required: true  %>
        </div>

        <div class="my-input">
          <div class="d-flex align-items-center">
            <%= f.check_box :rental_management %>
            <%= label_tag(:rental_management, "Gestion locative", class:"check-label") %>
          </div>

          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> La gestion locative permet à un tiers (souvent une agence immobilière) de gérer la recherche d'un locataire, le suivi du paiement des loyers ainsi que les contrôles périodiques de l'état du logement.
            <br />Il faut compter environ 7% du loyer ainsi qu'un mois de loyer par changement de locataire.  </p>
          </div>
        </div>

        <div class="my-input">
          <%= label_tag(:rental_vacancy, "Pourcentage de vacance locative (en %) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :rental_vacancy, class: 'form-control', value: @housing.rental_vacancy, min:"0", max:"100", required: true  %>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> Le pourcentage de vacance locative permet de prendre en compte dans nos calculs les périodes sans locataire (périodes entre le départ d'un locataire et l'arrivée d'un nouveau, etc.)<br />
            Une semaine de vacance locative représente 2% de vacance locative sur un an. <br /> <small>Pourcentage minimal conseillé: 6%</small> </p>
          </div>
        </div>

        <div class="my-input">      
          <%= label_tag(:maintenance_percentage, "Pourcentage de réserve pour entretien (en %) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :maintenance_percentage, class: 'form-control', value: @housing.maintenance_percentage, min:"0", max:"100", required: true  %>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> Le pourcentage de réserve permet de mettre chaque mois une somme de côté pour prendre en compte l'entretien à faire sur un logement. <br />
            Cette somme ne rentre pas en compte dans les bénéfices. <br /> <small>Pourcentage minimal conseillé: 2%</small> </p>
          </div>
        </div>
      </div>

      <div class="slide">
        <h6>Offre :</h6>

        <div class="my-input">
          <%= label_tag(:comment, "Vos remarques :") %>
          <%= f.text_area :comment, class: 'form-control', value: @housing.comment %>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> N'hésitez pas à visiter le logement à différents moments de la journée et de la semaine pour vérifier les éventuelles nuisances (bar, travaux, circulation...) présentes dans le quartier. </p>
          </div>       
        </div>

        <div class="my-input">
          <%= label_tag(:offer_price, "Prix de votre offre (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :offer_price, class: 'form-control', value: @housing.offer_price, min:"0", required: true  %>
          <div class="warning-area">
            <p><span style="font-size:1.2rem">&#9432;</span> Demandez les raisons de la vente du bien : si la vente est urgente, vous pourrez plus facilement négocier le prix.
            <br />Renseignez-vous sur la durée durant laquelle le propriétaire a vécu dans le bien : si le propriétaire habite ici depuis longtemps, il a eu davantage le temps de rembourser son crédit et sera surement davantage ouvert à une offre. </p>
          </div>
        </div>

        <div class="my-input">
          <%= label_tag(:notary_fees, "Frais de notaire (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :notary_fees, class: 'form-control', value: @housing.notary_fees, min:"0", required: true  %>
        </div>

        <div class="my-input">
          <%= label_tag(:agency_fees, "Frais d'agence (en €) :") %> <small class="text-secondary">minimum = 0 </small>
          <%= f.number_field :agency_fees, class: 'form-control', value: @housing.agency_fees, min:"0", required: true  %>
        </div>
      </div>
  
      <div class="form-footer">
        <button id="prev-btn"  style="display:none;"><i class="fas fa-chevron-circle-left"></i> Précédent</button>
        <button id="next-btn">Suivant <i class="fas fa-chevron-circle-right"></i></button>
        <button id="end-btn" style="display:none;">Finir</button>
      </div>
    </div>
  <%end%>
</div>

<%= javascript_include_tag 'form.js' %>

app/views/housings/new.html.erb
<section>
  <div class="py-15 d-flex flex-column container level-3 min-vh-100">
    <div class="row align-items-center justify-content-center my-auto">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <div class=" card-shadow">
          <div class="card-header bg-white pb-0">
            <%= link_to project_path(@project), class:'w-100 d-flex justify-content-start' do %>
              <i class="fas fa-arrow-left m-1">
              </i>  Retour
            <%end%>
            <h4 class="fw-light mb-5">Créer un nouveau <span class="fw-bold mb-5">logement </span></h4>
            <div>
              <div class="card-body">
                <%= form_with(model: @housing, url: project_housings_path, method: "post", local: true) do |f| %>
                  <form> 
                    <label for="property_category " class='mb-3'>Type de bien *:</label>
                    <select name="housing[property_category]" id="housing_property_category"><option value="Studio">Studio</option>
                      <option value="T1">T1</option>
                      <option value="T1bis">T1bis</option>
                      <option value="T2">T2</option>
                      <option value="T2bis">T2bis</option>
                      <option value="T3">T3</option>
                      <option value="T4">T4</option>
                      <option value="T5">T5</option>
                      <option value="T6">T6</option>
                      <option value="Immeuble">Immeuble</option>
                      <option value="Autre">Autre</option>
                    </select>
                    <div class="mb-3">
                      <label for="ad_price">Prix du logement * :</label>
                      <input class="form-control" type="number" name="housing[ad_price]" id="housing_ad_price">                      
                    </div>
                    <div class="mb-3">
                      <label for="localization">Localisation du bien *:</label>
                      <input class="form-control" type="text" name="housing[localization]" id="housing_localization">                     
                      <div class='col text-lg-end'>
                        <button type="submit" class="btn btn-primary rounded "  style="margin-top: 15px;">Créer</button>
                      </div>
                    </div>
                  </form>
                <% end %>               
              </div>            
            </div>
          </div>
        </div>
      </div>         
    </div>
  </div>
</section>

app/views/housings/show.html.erb
<div class="m-3">
  <%=link_to project_path(@housing.project_id) , class: 'btn btn-primary rounded  m-5' do%><i class="fas fa-arrow-left"></i> Retour <%end%>
</div>
<h1 style="text-align:center">FICHE DU LOGEMENT N°<%=params[:id]%> </h1> 
<div class="d-flex justify-content-end">
  <%= link_to "Editer", edit_project_housing_path(@housing.id), method: :get, class:'btn btn-primary rounded m-2 '%>
</div>
<div class="d-flex justify-content-center">
  <div class="card-border col-md-6" >
    <div class="card-body">
      <h3 class=" "style="text-align:center">RECAPITULATIF</h3>
      <div class="font-description">
        <p class="card-text">Prix de l'annonce : <%=@housing.ad_price%> €</p>
        <p><i class="fas fa-arrow-right"></i> Rentabilité nette en fonction du prix de l'annonce : <%=@housing.ad_profitability%> %)</p>
        <p> Prix de l'offre proposée : <%=@housing.offer_price%> €</p>
        <p> (<i class="fas fa-arrow-right"></i> Rentabilité nette en fonction du prix de l'offre : <%=@housing.offer_profitability%> %)</p>
        <p> Superficie habitable : <%=@housing.area%> m²</p>
        <p> Localisation : <%=@housing.localization%></p>
        <div>
          <p> Lien de l'annonce : <%=@housing.ad_url%></p>
          <p> Notes : <%=@housing.comment%></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="text-align:center" ><br /><br />
  <h4 class="" >CARACTERISTIQUES </h4> 
  <br />
</div>
<div class="container d-flex flex-column gap-25">
  <section >
    <div >
      <div class="row flex-md-column flex-lg-row gap-25 custom-col" id="first-row">
        <div class="col sm-6 m-6">
          <div class="card-border card-height">
            <div class="card-body ">
              <h3 class="" style="text-align:center ">Somme à financer </h3>
              <div class="font-description">
                <p> Prix de l'annonce : <%=@housing.ad_price%> €</p>
                <p> (Rentabilité nette : <%=@housing.ad_profitability%> )</p>
                <p> Prix de l'offre proposée : <%=@housing.offer_price%> €</p>
                <p> (Rentabilité nette : <%=@housing.offer_profitability%> )</p>
                <p> Prix des travaux : <%=@housing.repairs_price%> € </p>
                <p> Frais de notaire : <%=@housing.notary_fees%> €</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col sm-6 m-5">
          <div class="card-border card-height " >
            <div class="card-body">
              <h3 class="" style="text-align:center ">Caractéristiques du bien</h3>  
              <div class="font-description">
                <p> Surface habitable : <%=@housing.area%> m²</p> 
                <p> Type de bien : <%=@housing.property_category%></p> 
                <p> Localisation : <%=@housing.localization%></p> 
                <p> Bien neuf : <%if @housing.new_property == true %> Oui <%else%> Non <%end%> </p>
                <p> Prix des travaux : <%= @housing.repairs_price%>
              </div> 
            </div> 
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div>
      <div class="row flex-md-column flex-lg-row gap-25 custom-col" id="second-row">
        <div class="col sm-6 m-6">
          <div class="card-border card-height" >
            <div class="card-body ">
              <h3 class="" style="text-align:center ">Investissement </h3>
              <div class="font-description">
                <p> Loyer annuel complet: <%=@housing.annual_rent%></p>
                <p> Pourcentage de vacance locative : <%=@housing.rental_vacancy%> %</p>
                <p> Pourcentage de réserve pour entretien : <%=@housing.maintenance_percentage%> % </p>
                <p> Gestion locative : <%if @housing.rental_management === true%> Oui <%else%> Non <%end%></p>
              </div>
            </div>
          </div>
        </div>
        <div class="col sm-6 m-5">
          <div class="card-border card-height" >
            <div class="card-body">
              <h3 class="" style="text-align:center ">Charges</h3>  
              <div class="font-description">
                <p> Taxe d'habitation : <%=@housing.property_tax%> €</p>
                <p> Charges de copropriété : <%=@housing.building_co_tax%> €</p>
                <p> Assurance PNO : <%if @housing.pno_insurance === true%> Oui <%else%> Non <%end%> </p>
                <p> Assurance Loyers Impayés :  <%if @housing.rental_unpayment_insurance === true%> Oui <%else%> Non <%end%> </p>
              </div> 
            </div> 
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<%= javascript_include_tag 'show.js' %>