config/routes.rb
Rails.application.routes.draw do

  resources 'users',only:[:show], :path => "my-profile"
  resources 'projects', only:[:index,:new,:create,:show,:edit,:destroy,:update ], :path => "dashboard"
  resources :housings 
  scope 'admin', module: 'admin', as: 'admin' do
    resource 'pannel'
  end

  resources :projects do 
  resources :housings 
  end 

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  root to: "statics#home"

  scope controller: :statics do
    get :contact
    post :create
  
  end
end

app/views/layouts/_flash.html.erb
<div id="timer" class="flash" remote= true>
  <div style='position: relative; width: 100%'> 
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name %>' role="alert">
        <%= msg %>
      </div>
    <% end %>
  </div>
  <%= javascript_include_tag 'flash.js' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-10 py-xl-10">
  <div class="container">
    <div class="row g-4 g-lg-5 mb-10">
      <div class="col-md-3 text-center text-md-start">
        <%=link_to root_path, class:'navbar-brand d-flex flex-column align-items-center' do%>
          <%= image_tag "logo1.svg", style: "max-height:100px" %>
          <span style="font-family: 'Bakbak One', cursive; font-size: 3rem; color:black;">Immotep </span>    
        <%end%>
      </div>
      <div class="col">
        <ul class="list-unstyled">
          <li class="mb-1"><%= link_to 'Nous contacter', contact_path, class:'text-reset text-primary-hover' %></li>
          <li class="mb-1"><%= link_to 'Notre équipe', root_path(anchor: 'staff'), class:'text-reset text-primary-hover' %></li>
          <li class="mb-1"><%= link_to 'Recrutement', contact_path, class:'text-reset text-primary-hover' %></li>
          <li class="mb-1"><%= link_to 'Mentions légales', root_path, class:'text-reset text-primary-hover' %></li>
        </ul>
      </div>
      <div class="col-md-3 col-lg-3">
        <p class="small text-secondary">Cet outil représente plus de 600h de travail pour vous aider à investir. <br />
          Si vous appréciez notre travail, n'hésitez pas à nous payer un café, nous vous en remercions d'avance ! <br /> </p>
        <div class="grouped-inputs border border-primary p-1 rounded-pill">
          <div class="row">
            <div class="col">
              <p class="form-control rounded-pill px-3 text-primary">Payer un café</p>
            </div>
            <div class="col-auto">
              <%= button_to checkout_create_path(total: 3), class: "btn btn-primary btn-icon rounded-circle", remote: true do %>
                <i class="fas fa-coffee"></i>
              <% end %>
            </div>
          </div>            
        </div>
      </div>
      <div class="col col-lg-3 d-flex justify-content-center">
        <a href="#top"><i class="fas fa-arrow-circle-up fa-3x"></i></a>
      </div>
    </div>
    <div class="row align-items-center g-1 g-lg-6">
      <div class="col-md-6 col-lg-5 order-lg-2 text-center text-md-start">
        <ul class="list-inline small">
          <li class="list-inline-item"><a href="https://github.com/ophelie-gaudin/Immo-Invest" class="text-reset text-primary-hover">github</a></li>
          <li class="list-inline-item ms-1"><a href="https://twitter.com/the_hacking_pro" class="text-reset text-primary-hover">twitter</a></li>
          <li class="list-inline-item ms-1"><a href="https://www.linkedin.com/school/the_hacking_project/" class="text-reset text-primary-hover">linkedin</a></li>
        </ul>
      </div>
      <div class="col-md-6 col-lg-4 text-center text-md-end order-lg-3">
        <span class="small">10 boulevard des corsaires, THP Paris CEDEX 42</span>
      </div>
      <div class="col-lg-3 order-lg-1 text-center text-md-start">
        <p class="small">IMMOTEP © 2021</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-expand-lg navbar-sticky navbar-light navbar-sticky  position-fixed" >
  <div class="container">

    <div>
      <%=link_to root_path, class:'navbar-brand' do %><%= image_tag "logo1.svg", style: "max-height:40px" %>
      <span style="font-family: 'Bakbak One', cursive; margin-left: 20px;">Immotep </span> 
      <% end %>  
    </div>
  
    <div class="collapse navbar-collapse" data-bs-parent="#mainNav">
      <ul class="navbar-nav w-100">

        <% if isAdmin? %>

        <li class="nav-item">
          <p class="nav-link" role="button"
            aria-expanded="false">
            <%= link_to 'Pannel Administration', admin_pannel_path %>
          </p>
        </li>

        <%end%>

        <% if isUser? %>
      
        <li class="nav-item ">
            <%=link_to 'Mes projets',projects_path, {class:'nav-link', :role => 'button', 'aria-expanded' => 'false'} %>
        </li>

        <% else %>

        <div class="w-100 d-flex justify-content-end">
            <%=link_to 'Connexion',new_user_session_path, {class:'nav-link', :role => 'button', 'aria-expanded' => 'false'} %>
          </li>

          <li class="nav-item">
            <%=link_to 'Inscription',new_user_registration_path, {class:'nav-link', :role => 'button', 'aria-expanded' => 'false'} %>
          </li>
        </div>

        <%end%>

      </ul>
    </div>

    
    <ul class="navbar-nav navbar-nav-secondary order-lg-3">
      
      
      <% if isAdmin? %>

        <li class="nav-item d-lg-none">
          <%link_to admin_pannel_path, class:'nav-link nav-icon', role:'button' do %><i class="fas fa-users-cog" title="Pannel Administration"></i> <% end %>
        </li>

      <%end%>

      <% if isUser? %>

      <li class="nav-item dropdown dropdown-hover d-lg-block">
        <%= link_to user_path(current_user), {class:'nav-link nav-icon', :role => 'button', 'id' => 'dropdownMenuButton1', 'data-bs-toggle' => 'dropdown', 'aria-expanded' => 'false' } do %>
        <i class="fa-solid fa-user"></i>
        <% end %> 

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><%=link_to 'Mes informations',user_path(current_user), class:'dropdown-item'%></li>
          <li><%=link_to 'Déconnexion',destroy_user_session_path , {class:'dropdown-item text-red','data-method' =>'delete'} %></li>
        </ul>  
      </li>
      
      
      <li class="nav-item d-lg-none">
        <%=link_to projects_path, {class:'nav-link nav-icon', :role => 'button', 'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation' } do %>
        <i class="fas fa-book" title="Mes projets"></i>
        <% end %> 
      </li>

      <li class="nav-item d-lg-none">
        <%=link_to destroy_user_session_path , {class:'dropdown-item text-red',:role => 'button','data-method' =>'delete'} do%>
          <i class="fas fa-times" title= "Déconnexion"></i>
        <% end %>
      </li>
    
      <%else%>

      <li class="nav-item d-lg-none">
        <%=link_to new_user_registration_path, {class:'nav-link nav-icon', :role => 'button', 'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation','data-bs-toggle' => 'collapse','data-bs-target' => '#navbar'} do %>
        <i class="fa-solid fa-user" title="Inscription"></i>
        <% end %> 
      </li>

    </ul>
    
    <%end%>


  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>ImmoTep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet"> 
    <script src="https://js.stripe.com/v3/"></script>

  </head>


  <body>

      <%= render 'layouts/navbar' %> 
      <%= render 'layouts/flash'%>

    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
    
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script> AOS.init(); </script>
  </body>
</html>